### ISSUE TITLE
invalid nonce parameter; on key:3461320759, you sent:'10', you should send:3461320760

### ISSUE THREAD

**Issue by xaionaro** [marinu666/PHP-btce-api#6]
```
PHP Notice:  Nonce we sent (1440851355) is invalid, retrying request with server returned nonce: (9)! in /home/xaionaro/PHP-btce-api/btce-api.php on line 100
PHP Fatal error:  Uncaught exception 'BTCeAPIErrorException' with message 'API Error Message: invalid nonce parameter; on key:3461320759, you sent:'10', you should send:3461320760. Response: Array
(
    [success] => 0
    [error] => invalid nonce parameter; on key:3461320759, you sent:'10', you should send:3461320760
)
' in /home/xaionaro/PHP-btce-api/btce-api.php:104
Stack trace:
#0 /home/xaionaro/PHP-btce-api/btce-api.php(102): BTCeAPI->apiQuery('getInfo', Array)
#1 /home/xaionaro/PHP-btce-api/trader.php(8): BTCeAPI->apiQuery('getInfo')
#2 {main}
  thrown in /home/xaionaro/PHP-btce-api/btce-api.php on line 104
```

**Comment by xaionaro** [comment]
Deleted the API key and created a new one -- fixed the problem. However there's an error in the code causes wrong "noonce" on retry (`you sent:'10'`).
